FROM node:8-slim
RUN curl -fsSL https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
        && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list \
        && apt-get update \
        && apt-get install -y google-chrome-stable netcat --no-install-recommends \
        && rm -rf /var/lib/apt/lists/*
COPY bin/wait-for /usr/local/bin/wait-for
RUN chmod +x /usr/local/bin/wait-for
VOLUME [ "/app" ]
WORKDIR /app
CMD [ "bash" ]